# run: conda env create --file environment.yml

name: realestenv
dependencies:
- python==3.8
- pandas==1.5.3
- numpy
- install scikit-learn
- pip
- pip:
  # works for regular pip packages
  - jupyter
  - matplotlib
  - seaborn
  - openpyxl